version: '3.2'
services: 
    nginx:
        image: nginx
        ports: 
            - 80:80
        container_name: nginx
        depends_on: 
            - flask
        networks: 
            - my-network
        volumes: 
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
    flask:
        build: 
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/code/
        environment:
            - FLASK_APP=/code/main.py
        command: uwsgi --ini /code/uwsgi.ini
        ports:
            - 8080:5000   
        networks: 
            my-network:
                aliases:
                    - flask-app       
networks: 
    my-network:
