version: '3.2'
services: 

    flask:
        build: 
            context: ./flask
            
        image: py_uwsgi_manh_flask
        volumes:
            - ./:/code/
        environment:
            - FLASK_APP=/code/run.py
        command: uwsgi --ini /code/flask/app.ini
        ports:
            - "8081:5000"   
#         networks: 
#             my-network:
#                 aliases:
#                     - flask-app       
# networks: 
#     my-network:
